export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';
export const GET_USERS_LOADIND = 'GET_USERS_LOADIND';

export const AUTHTICATION = 'AUTHTICATION';

export const SET_CHAT_ROOMS = 'SET_CHAT_ROOMS';
export const SET_PRIVATE_CHAT = 'SET_PRIVATE_CHAT';
